### ISSUE TITLE
Question: Is this library published?

### ISSUE THREAD

**Issue by mrollo** [nishkarsh/android-permissions#10]
Hi, this isn't a bug, just a question. I can't find this library in maven central or bintray. Do you publish this library anywhere so that we can consume it without having to download and build the source?

Thanks!

**Comment by mrollo** [comment]
Thank you. I had searched for your artifact in bintray's site, but couldn't find it. But if you add jcenter() as a repository and the implementation line to your dependencies, it does work.

**Comment by christocracy** [comment]
It’s not mine.  I’m just a user, like you.
