### ISSUE TITLE
How do i test from Activity for onPermissionDenied() it cannot be invoked.  i cannot make an object of PermissionHandler class

### ISSUE THREAD

**Issue by suman8848** [nishkarsh/android-permissions#11]
For any issues that you report in the android-permissions library, please use this format:

#### Bug Report

Providing detailed feedback would help in quickly resolving the issue. Following the below format would ensure that enough detail is provided so that the valid bug can be reproduced easily.

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
* Expected behavior:
* Android API Version:
* Android Device (include Model and Manufacturer):
* Link to sample code (not always needed):

**Comment by suman8848** [comment]
PermissionManager permissionManager = PermissionManager.getInstance(testObject);
    PermissionManager.PermissionRequestListener requestListener =
        mock(PermissionManager.PermissionRequestListener.class);
    testObject.checkRuntimePermission();
    permissionManager.checkPermissions(permissionStringList, requestListener);
    verify(requestListener).onPermissionDenied();
**I tried this approach it's invoking onPremissionGranted(); but how would i test it for onPermissionDenied(). I am having following error on logcat.

Wanted but not invoked:
permissionRequestListener.onPermissionDenied();
However, there was exactly 1 interaction with this mock:
permissionRequestListener.onPermissionGranted();-> at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:41)

**Comment by hpsaturn** [comment]
I have the same situation but on `onPermissionGranted` with:

``` java
public void checkForPermissions() {
        PermissionManager permissionManager = PermissionManager.getInstance(this);
        ArrayList<String> permissions = new ArrayList<>();
        permissions.add(Manifest.permission.ACCESS_COARSE_LOCATION);
        permissions.add(Manifest.permission.INTERNET);
        permissions.add(Manifest.permission.ACCESS_NETWORK_STATE);
        permissions.add(Manifest.permission.WRITE_EXTERNAL_STORAGE);
        permissions.add(Manifest.permission.ACCESS_COARSE_LOCATION);
        permissions.add(Manifest.permission.ACCESS_FINE_LOCATION);
        permissions.add(Manifest.permission.ACCESS_WIFI_STATE);
        permissions.add(Manifest.permission.FOREGROUND_SERVICE);
        permissionManager.checkPermissions(permissions, new PermissionManager.PermissionRequestListener() {
            @Override
            public void onPermissionGranted() {
                Logger.i(TAG, "onPermissionGranted..");  // <== *** NEVER REACHED ***
                setupUI();
                startDataBase();
            }

            @Override
            public void onPermissionDenied() {
            }
        });
    }
```
- Android application parameters:
```
mCompileSdkVersion=28
mMinSdkVersion=19
mTargetSdkVersion=28
android.useAndroidX=true
android.enableJetifier=true
```
 
- Device: OnePlus 6

**Comment by nishkarsh** [comment]
@hpsaturn This is most probably because either these permissions have not been mentioned in AndroidManifest.xml or because of `      permissions.add(Manifest.permission.FOREGROUND_SERVICE);
`. According to the documentation, `FOREGROUND_SERVICE` is a normal permission and you don't really have to ask it dynamically. The system grants it automatically when defined in AndroidManifest.xml. Also, you don't need to ask for any other permissions that are normal.
