### ISSUE TITLE
Notification channel not registered on API27

### ISSUE THREAD

**Issue by mauron85** [nishkarsh/android-permissions#12]
#### Bug report

If PermissionManager is called when app is in foreground everything works ok - dialog is show.

But when app is in background, no notification is shown (and according to docs:
`In case permissions are not yet provided, user would be asked for permissions (a dialog in case app is in foreground, a notification in case it's in background)`) it should.

Instead following error is found in adb log:
```
NotificationService: No Channel found for pkg=xxx, channelId=android-permissions, id=-1951610903, tag=[android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION], ...)
```

The reason is that this plugin is using channels, but not registering them with `NotificationManager. createNotificationChannel`

* Steps to reproduce the problem
Call PermissionManager checkPermissions when app is in background

* Expected behavior:
Notification should shown with Allow action

* Android API Version:
API 27 (Oreo)

* Android Device (include Model and Manufacturer):
any

* Link to sample code (not always needed):

**Comment by nishkarsh** [comment]
Hey @mauron85,
Thanks for reporting this issue. This is fixed in release version 0.1.8.
