### ISSUE TITLE
Logging occasional ConcurrentModificationException errors

### ISSUE THREAD

**Issue by mikejeep** [nishkarsh/android-permissions#16]
My crash reporting tools are logging dozens of `ConcurrentModificationException` exceptions related to this library (2.0.49). Reports are from various devices including different Samsung, Google, OnePlus, and Xiaomi models. The consistent factor does appear to be that all devices appear to be running Android 10. Unfortunately all I can offer is the raw error output, as I am unable to reproduce the error myself. The log output is identical on all devices except some line numbers for the OS methods are slightly different. Here is an example from a Google device:

    java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextNode (HashMap.java:1441)
     at java.util.HashMap$KeyIterator.next (HashMap.java:1465)
     at com.intentfilter.androidpermissions.PermissionHandler.informPermissionsGranted (PermissionHandler.java:114)
     at com.intentfilter.androidpermissions.PermissionHandler.onPermissionsResult (PermissionHandler.java:56)
     at com.intentfilter.androidpermissions.PermissionManager.onReceive (PermissionManager.java:60)
     at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts (LocalBroadcastManager.java:313)
     at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage (LocalBroadcastManager.java:121)
     at android.os.Handler.dispatchMessage (Handler.java:107)
     at android.os.Looper.loop (Looper.java:214)
     at android.app.ActivityThread.main (ActivityThread.java:7356)
     at java.lang.reflect.Method.invoke (Method.java)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
     at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)

**Comment by christocracy** [comment]
@nishkarsh Probably related to not accessing stuff like [pendingPermissionRequests](https://github.com/nishkarsh/android-permissions/blob/master/src/main/java/com/intentfilter/androidpermissions/PermissionHandler.java#L58) within `synchronized` block, eg:

```java
synchronized(pendingPermissionRequests) {
    pendingPermissionRequests.removeAll(asList(grantedPermissions));
    pendingPermissionRequests.removeAll(deniedPermissions.stripped());
    if (pendingPermissionRequests.isEmpty()) {
        manager.unregisterBroadcastReceiver();
    }
}
```

**Comment by mikejeep** [comment]
I edited my original comment with a better crash report that did not have any methods obfuscated.

**Comment by nishkarsh** [comment]
@mikejeep thanks for reporting this! @christocracy thanks for investigating it a bit! I would be soon back to work from a short vacation and look into this! Perhaps a test would be able to reproduce this and verify the fix.

**Comment by christocracy** [comment]
A test to reproduce this will have multiple permission requests on different threads.

This is a multi-threading issue.

**Comment by mikejeep** [comment]
Any updates on this? Thanks!

**Comment by nishkarsh** [comment]
Unfortunately, I have not been able to spend time on this one yet. I would look into is ASAP.

**Comment by mikejeep** [comment]
@nishkarsh I know you are busy, I just saw on another issue that you have taken donations in the past. I would be happy to make a contribution if that will help accelerate the resolution of this bug. I am logging a lot of these exceptions from my users and would like to resolve it.

**Comment by nishkarsh** [comment]
Hey @mikejeep, I will look into this one today. Other internal projects had been keeping me busy but it has been pending for way too long.

**Comment by nishkarsh** [comment]
Hey @mikejeep! Fortunately, I was able to reproduce this issue and verify the fix with a unit test. You should upgrade the dependency to version 2.0.54 in which the issue is resolved. You should eventually stop seeing these errors from the users of your app.

Thanks again for reporting this!

**Comment by mikejeep** [comment]
Thank you @nishkarsh! I will update my app today and monitor the exception logging, once I'm confident it's no longer an issue I will close this issue out. I'd like to send you a contribution as thanks for your efforts if you could provide the preferred way to do that.

**Comment by nishkarsh** [comment]
Yes, since the issue was at multiple places, give it some time in production to verify that all of those places have been patched.

You can now see a `Sponser` label in the menu on top in the repository that you could use to donate an amount of your choice. Thanks for supporting the library!

**Comment by mikejeep** [comment]
This appears to be resolved, the error reports have disappeared. I appreciate your time and going to go hit that Sponsor page now, thanks!
