### ISSUE TITLE
Crash when permissions denied

### ISSUE THREAD

**Issue by UglyBlueCat** [nishkarsh/android-permissions#23]
Hi,

I am using an npm plugin that uses android-permissions 0.1.8

When permissions are denied, my app crashes at PermissionHandler.java:102

I can see that your library has been developed well past 0.1.8

Has this bug already been fixed?

Can you give me the lowest version number at which it is fixed?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.okappy.okappy, PID: 28732
    java.lang.AbstractMethodError: abstract method "void com.intentfilter.androidpermissions.PermissionManager$PermissionRequestListener.onPermissionDenied(com.intentfilter.androidpermissions.models.DeniedPermissions)"
        at com.intentfilter.androidpermissions.PermissionHandler.informPermissionsDenied(PermissionHandler.java:102)
        at com.intentfilter.androidpermissions.PermissionHandler.onPermissionsResult(PermissionHandler.java:57)
        at com.intentfilter.androidpermissions.PermissionManager.onReceive(PermissionManager.java:60)
```

Thank you in advance for any help you are able to give me.

Robin

**Comment by nishkarsh** [comment]
Hey Robin! This doesn't indicate a problem in the implementation of the original library but the way it's being used. There seems to be a mismatch in the dependency version that the npm plugin might be using and the implementation of the request listener that it has defined.

**Comment by UglyBlueCat** [comment]
Hi Nish,

Thank you for your speedy response!

Hopefully this will result in a resolution to my issue.

I will keep you posted.

Thanks :)
Robin

**Comment by UglyBlueCat** [comment]
Thank you for your help with this.

The issue was resolved with a new cordova project
