### ISSUE TITLE
Api not adjusted to android-31 target. 

### ISSUE THREAD

**Issue by hatched-mariusz** [nishkarsh/android-permissions#25]
### Crash on android-31 target

```
Fatal Exception: java.lang.IllegalArgumentException: com.xxxxxxxx.apps.xxxxxxx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
       at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
       at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
       at com.intentfilter.androidpermissions.PermissionManager.notificationDismissIntent(PermissionManager.java:105)
```

**Comment by nishkarsh** [comment]
I think I already have an MR related to this from you, but there are multiple changes clubbed in a single commit so I need to look at it. Also, I need time to test the changes and also ensure that the build pipeline passes for it. I should be able to get this merged over the weekend.

**Comment by nishkarsh** [comment]
This issue should be fixed in version 2.1.5, it has been released and should be synced with maven central in some time.

**Comment by GavynHolt** [comment]
Is there any update on this release in Maven? Currently I am seeing v.2.0.54 as the latest on Maven but 2.1.8 in the repo releases. I am also experiencing the `FLAG_IMMUTABLE` issue with PendingIntents and would love to upgrade to the latest.

**Comment by nishkarsh-beamery** [comment]
Hey @GavynHolt, the version 2.1.8 was published 8 months ago. You can find it in the Maven Central repo here: https://central.sonatype.dev/artifact/io.github.nishkarsh/android-permissions/2.1.8

**Comment by GavynHolt** [comment]
Ahh I see the package now, thank you very much! An old colleague had been using `com.intentfilter:android-permissions` , but I see now that that you have migrated to the `io.github.nishkarsh:android-permissions`

**Comment by christocracy** [comment]
It comes from the permissions library the plug-in uses.   No, it’s not
daily configurable.

https://github.com/nishkarsh/android-permissions
