### ISSUE TITLE
Add ability to set color of notification

### ISSUE THREAD

**Issue by astromme** [nishkarsh/android-permissions#37]
Hello!

Love that the latest release supports setting the notification icon. Would you consider adding support for setting the color as well? It appears that this could be done when setting up the Builder in `NotificationService.java` and exposed to the API caller similarly to `.withSmallIcon()`.

```
     NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(context, CHANNEL_ID)
                .setContentTitle(title)
                .setContentText(message)
                .setAutoCancel(true)
                .setPriority(NotificationCompat.PRIORITY_DEFAULT)
                .setSmallIcon(smallIconResId)
                .setContentIntent(pendingIntent);
```

Thanks!

Andrew

**Comment by astromme** [comment]
@nishkarsh I created a PR that implements this change. Would you be open to reviewing and merging it? Happy to make any adjustments as needed.

**Comment by nishkarsh** [comment]
Hey Andrew! Thanks for raising this issue and also creating the PR for this, I have some feedback on the same. I agree that we should have this capability in the lib, let's just finalise the change and I would be happy to merge it.
