### ISSUE TITLE
application@allowBack is required by the plugin

### ISSUE THREAD

**Issue by christocracy** [nishkarsh/android-permissions#6]
Does this library use the application attribute [`allowBackup`](https://github.com/nishkarsh/android-permissions/blob/master/src/main/AndroidManifest.xml#L5)

Can it be removed?

Implementing the library in an App which *also* defines this attribute requires some `tools:replace` fiddling:

```
/app/src/main/AndroidManifest.xml:11:7-34 Error:
        Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [com.intentfilter:android-permissions:0.1.5] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-24:19 to override.
```

**Comment by christocracy** [comment]
I'm a library author as well.  Your lib is a dependency of mine.

Here's my `<application>` element in my lib:
```xml
<application android:label="@string/app_name">
```

**Comment by nishkarsh** [comment]
@christocracy That's the correct thing to have. This issue should be fixed in version 0.1.6.

**Comment by christocracy** [comment]
Thanks for the quick release.  Do you have a PayPal link?

**Comment by nishkarsh** [comment]
@christocracy You're welcome! And yes, I do. Here it is [https://www.paypal.me/nishkarsh4](https://www.paypal.me/nishkarsh4). Thanks if you are considering a donation :)
